const LOGIN_USER_SUCCESSFUL = 'LOGIN_USER_SUCCESSFUL';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
const LOGOUT_USER = "LOGOUT_USER";
const REGISTER_USER = 'REGISTER_USER';
const REQUEST_POKEMONS = 'REQUEST_POKEMONS';
const REQUEST_POKEMONS_FAILURE = 'REQUEST_POKEMONS_FAILURE';
const REQUEST_POKEMONS_SUCCESSFUL = 'REQUEST_POKEMONS_SUCCESSFUL';
const REQUEST_POKEMON_DETAIL = 'REQUEST_POKEMON_DETAIL';
const REQUEST_POKEMON_DETAIL_SUCCESSFUL = 'REQUEST_POKEMON_DETAIL_SUCCESSFUL';
const REQUEST_POKEMON_DETAIL_FAILURE = 'REQUEST_POKEMON_FAILURE';
const RESET_POKEMON_DETAIL = 'RESET_POKEMON_DETAIL';

export {
  LOGIN_USER_SUCCESSFUL,
  LOGIN_USER_FAILURE,
  LOGOUT_USER,
  REGISTER_USER,
  REQUEST_POKEMONS,
  REQUEST_POKEMONS_FAILURE,
  REQUEST_POKEMONS_SUCCESSFUL,
  REQUEST_POKEMON_DETAIL,
  REQUEST_POKEMON_DETAIL_SUCCESSFUL,
  REQUEST_POKEMON_DETAIL_FAILURE,
  RESET_POKEMON_DETAIL
};
